In [1]:
import numpy as np

# 1. Compare two friends' daily steps over a week
friend1_steps = np.array([8000, 9000, 7500, 8500, 9200, 7800, 8800])
friend2_steps = np.array([7600, 8700, 8200, 7900, 9100, 8000, 8600])

print("Friend 1 steps:", friend1_steps)
print("Friend 2 steps:", friend2_steps)
print("Addition:", friend1_steps + friend2_steps)
print("Subtraction:", friend1_steps - friend2_steps)
print("Multiplication:", friend1_steps * friend2_steps)
print("Division:", friend1_steps / friend2_steps)

# 2. Spotify-like recommendation matrix using dot() and matmul()
user_preferences = np.array([
    [3, 4, 2],
    [1, 5, 3],
    [4, 2, 5]
])
song_popularity = np.array([
    [2, 1, 3],
    [4, 2, 1],
    [3, 5, 2]
])

recommendation_dot = user_preferences.dot(song_popularity)
recommendation_matmul = np.matmul(user_preferences, song_popularity)

print("\nRecommendation via dot():")
print(recommendation_dot)
print("\nRecommendation via matmul():")
print(recommendation_matmul)
# For 2D arrays, dot() and matmul() produce the same result; matmul() is more explicit and is preferred for matrix multiplication.

# 3. Rotate a small Instagram image using transpose
pixel_brightness = np.array([
    [120, 130, 140, 150],
    [110, 125, 135, 145],
    [100, 115, 123, 137],
    [90, 105, 112, 128]
])
rotated_image = pixel_brightness.T

print("\nTransposed image:")
print(rotated_image)
print("Mean:", pixel_brightness.mean())
print("Median:", np.median(pixel_brightness))
print("Standard deviation:", pixel_brightness.std())
print("Variance:", pixel_brightness.var())

# 4. Zomato restaurant rating correlation matrix
restaurant_corr = np.array([
    [4.0, 1.0, 2.0],
    [0.0, 3.0, 1.0],
    [1.0, 0.0, 2.0]
])

inverse_matrix = np.linalg.inv(restaurant_corr)
determinant = np.linalg.det(restaurant_corr)
eigenvalues, eigenvectors = np.linalg.eig(restaurant_corr)

print("\nInverse matrix:")
print(inverse_matrix)
print("Determinant:", determinant)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

# 5. Swiggy orders over 6 days for two cities
orders = np.array([
    [10, 20, 15, 30, 25, 18],
    [12, 18, 22, 28, 16, 24]
])

reshaped_orders = orders.reshape(3, 4)
flattened_orders = reshaped_orders.flatten()
first_half, second_half = np.array_split(flattened_orders, 2)
vertical_stack = np.vstack((first_half, second_half))

print("\nReshaped orders:")
print(reshaped_orders)
print("Flattened orders:", flattened_orders)
print("First half:", first_half)
print("Second half:", second_half)
print("Vertically stacked parts:")
print(vertical_stack)


Friend 1 steps: [8000 9000 7500 8500 9200 7800 8800]
Friend 2 steps: [7600 8700 8200 7900 9100 8000 8600]
Addition: [15600 17700 15700 16400 18300 15800 17400]
Subtraction: [ 400  300 -700  600  100 -200  200]
Multiplication: [60800000 78300000 61500000 67150000 83720000 62400000 75680000]
Division: [1.05263158 1.03448276 0.91463415 1.07594937 1.01098901 0.975
 1.02325581]

Recommendation via dot():
[[28 21 17]
 [31 26 14]
 [31 33 24]]

Recommendation via matmul():
[[28 21 17]
 [31 26 14]
 [31 33 24]]

Transposed image:
[[120 110 100  90]
 [130 125 115 105]
 [140 135 123 112]
 [150 145 137 128]]
Mean: 122.8125
Median: 124.0
Standard deviation: 16.24891823322402
Variance: 264.02734375

Inverse matrix:
[[ 0.31578947 -0.10526316 -0.26315789]
 [ 0.05263158  0.31578947 -0.21052632]
 [-0.15789474  0.05263158  0.63157895]]
Determinant: 18.999999999999996
Eigenvalues: [4.87938524+0.j 1.46791111+0.j 2.65270364+0.j]
Eigenvectors:
[[-0.93057968+0.j -0.40700082+0.j  0.20938838+0.j]
 [-0.17196417+0