In [ ]:
import numpy as np

# 1. Instagram followers
followers = np.array([1200, 15000, 67000, 340000, 1250000])
print("Followers array:", followers)
print("Shape:", followers.shape)
print("Number of dimensions:", followers.ndim)
print("Data type:", followers.dtype)

# 2. Zomato order IDs
order_ids = np.arange(101, 111)
print("Order IDs:", order_ids)
print("Size:", order_ids.size)

# 3. Like identity matrix
like_identity = np.eye(3)
print("Like identity matrix:")
print(like_identity)
# The diagonal values represent the identity relationship: each item matches itself with a value of 1.

# 4. Cricket scores
cricket_scores = [45, 67, 120, 89, 54]
cricket_scores_array = np.array(cricket_scores)
print("Cricket scores array:", cricket_scores_array)
print("Itemsize:", cricket_scores_array.itemsize, "bytes")


Followers array: [   1200   15000   67000  340000 1250000]
Shape: (5,)
Number of dimensions: 1
Data type: int64
Order IDs: [101 102 103 104 105 106 107 108 109 110]
Size: 10
Like identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Cricket scores array: [ 45  67 120  89  54]
Itemsize: 8 bytes
