In [1]:
import numpy as np

# 1. Zomato food ratings: 4 users x 5 food items
ratings = np.array([
    [4, 5, 3, 4, 2],
    [3, 4, 5, 2, 4],
    [5, 3, 4, 5, 3],
    [2, 4, 3, 3, 5]
])

# Slicing to extract ratings of the second and third users only
selected_users = ratings[1:3, :]
print("Ratings of users 2 and 3:")
print(selected_users)

# 2. Daily steps with boolean indexing
steps = np.array([7500, 8200, 9000, 7800, 9500, 8100, 8700, 7600, 9100, 8300])
high_steps = steps[steps > 8000]
print("\nDays with steps greater than 8000:")
print(high_steps)

# 3. IPL team scores using fancy indexing
ipl_scores = np.array([180, 210, 155, 240, 198, 176, 220, 190])
selected_scores = ipl_scores[[1, 4, 6]]
print("\nScores from matches 2, 5, and 7:")
print(selected_scores)

# 4. Flipkart product prices with broadcasting
product_prices = np.array([1000, 2500, 4000, 1500, 3000])
discounted_prices = product_prices * 0.9
print("\nDiscounted prices:")
print(discounted_prices)

# 5. Spotify song ratings: set negative ratings to zero
song_ratings = np.array([4, -1, 0, 3, -2, 5])
song_ratings[song_ratings < 0] = 0
print("\nUpdated song ratings:")
print(song_ratings)


Ratings of users 2 and 3:
[[3 4 5 2 4]
 [5 3 4 5 3]]

Days with steps greater than 8000:
[8200 9000 9500 8100 8700 9100 8300]

Scores from matches 2, 5, and 7:
[210 198 220]

Discounted prices:
[ 900. 2250. 3600. 1350. 2700.]

Updated song ratings:
[4 0 0 3 0 5]
